version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    x-aws-pull_credentials: your-arn-for-your-secret # <<<your arn for your secret you can get with docker ecs secret list>>>
    image: cpheinrich/fastapi-example # Replace your-docker-hub-username before deploying
    ports:
      - "80:80"
